// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: grpc_testify

package grpc_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/grpc/interop/grpc_testing"
)

// NewMockTestServiceServer creates a new instance of MockTestServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestServiceServer {
	mock := &MockTestServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTestServiceServer is an autogenerated mock type for the TestServiceServer type
type MockTestServiceServer struct {
	grpc_testing.UnimplementedTestServiceServer
	mock.Mock
}

type MockTestServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestServiceServer) EXPECT() *MockTestServiceServer_Expecter {
	return &MockTestServiceServer_Expecter{mock: &_m.Mock}
}

// CacheableUnaryCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) CacheableUnaryCall(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error) {
	ret := _mock.Called(context1, simpleRequest)

	if len(ret) == 0 {
		panic("no return value specified for CacheableUnaryCall")
	}

	var r0 *grpc_testing.SimpleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error)); ok {
		return returnFunc(context1, simpleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.SimpleRequest) *grpc_testing.SimpleResponse); ok {
		r0 = returnFunc(context1, simpleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc_testing.SimpleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc_testing.SimpleRequest) error); ok {
		r1 = returnFunc(context1, simpleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestServiceServer_CacheableUnaryCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheableUnaryCall'
type MockTestServiceServer_CacheableUnaryCall_Call struct {
	*mock.Call
}

// CacheableUnaryCall is a helper method to define mock.On call
//   - context1 context.Context
//   - simpleRequest *grpc_testing.SimpleRequest
func (_e *MockTestServiceServer_Expecter) CacheableUnaryCall(context1 interface{}, simpleRequest interface{}) *MockTestServiceServer_CacheableUnaryCall_Call {
	return &MockTestServiceServer_CacheableUnaryCall_Call{Call: _e.mock.On("CacheableUnaryCall", context1, simpleRequest)}
}

func (_c *MockTestServiceServer_CacheableUnaryCall_Call) Run(run func(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest)) *MockTestServiceServer_CacheableUnaryCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc_testing.SimpleRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc_testing.SimpleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_CacheableUnaryCall_Call) Return(simpleResponse *grpc_testing.SimpleResponse, err error) *MockTestServiceServer_CacheableUnaryCall_Call {
	_c.Call.Return(simpleResponse, err)
	return _c
}

func (_c *MockTestServiceServer_CacheableUnaryCall_Call) RunAndReturn(run func(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error)) *MockTestServiceServer_CacheableUnaryCall_Call {
	_c.Call.Return(run)
	return _c
}

// EmptyCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) EmptyCall(context1 context.Context, empty *grpc_testing.Empty) (*grpc_testing.Empty, error) {
	ret := _mock.Called(context1, empty)

	if len(ret) == 0 {
		panic("no return value specified for EmptyCall")
	}

	var r0 *grpc_testing.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.Empty) (*grpc_testing.Empty, error)); ok {
		return returnFunc(context1, empty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.Empty) *grpc_testing.Empty); ok {
		r0 = returnFunc(context1, empty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc_testing.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc_testing.Empty) error); ok {
		r1 = returnFunc(context1, empty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestServiceServer_EmptyCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmptyCall'
type MockTestServiceServer_EmptyCall_Call struct {
	*mock.Call
}

// EmptyCall is a helper method to define mock.On call
//   - context1 context.Context
//   - empty *grpc_testing.Empty
func (_e *MockTestServiceServer_Expecter) EmptyCall(context1 interface{}, empty interface{}) *MockTestServiceServer_EmptyCall_Call {
	return &MockTestServiceServer_EmptyCall_Call{Call: _e.mock.On("EmptyCall", context1, empty)}
}

func (_c *MockTestServiceServer_EmptyCall_Call) Run(run func(context1 context.Context, empty *grpc_testing.Empty)) *MockTestServiceServer_EmptyCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc_testing.Empty
		if args[1] != nil {
			arg1 = args[1].(*grpc_testing.Empty)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_EmptyCall_Call) Return(empty1 *grpc_testing.Empty, err error) *MockTestServiceServer_EmptyCall_Call {
	_c.Call.Return(empty1, err)
	return _c
}

func (_c *MockTestServiceServer_EmptyCall_Call) RunAndReturn(run func(context1 context.Context, empty *grpc_testing.Empty) (*grpc_testing.Empty, error)) *MockTestServiceServer_EmptyCall_Call {
	_c.Call.Return(run)
	return _c
}

// FullDuplexCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) FullDuplexCall(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error {
	ret := _mock.Called(bidiStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for FullDuplexCall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error); ok {
		r0 = returnFunc(bidiStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestServiceServer_FullDuplexCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullDuplexCall'
type MockTestServiceServer_FullDuplexCall_Call struct {
	*mock.Call
}

// FullDuplexCall is a helper method to define mock.On call
//   - bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]
func (_e *MockTestServiceServer_Expecter) FullDuplexCall(bidiStreamingServer interface{}) *MockTestServiceServer_FullDuplexCall_Call {
	return &MockTestServiceServer_FullDuplexCall_Call{Call: _e.mock.On("FullDuplexCall", bidiStreamingServer)}
}

func (_c *MockTestServiceServer_FullDuplexCall_Call) Run(run func(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse])) *MockTestServiceServer_FullDuplexCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]
		if args[0] != nil {
			arg0 = args[0].(grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_FullDuplexCall_Call) Return(err error) *MockTestServiceServer_FullDuplexCall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestServiceServer_FullDuplexCall_Call) RunAndReturn(run func(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error) *MockTestServiceServer_FullDuplexCall_Call {
	_c.Call.Return(run)
	return _c
}

// HalfDuplexCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) HalfDuplexCall(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error {
	ret := _mock.Called(bidiStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for HalfDuplexCall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error); ok {
		r0 = returnFunc(bidiStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestServiceServer_HalfDuplexCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HalfDuplexCall'
type MockTestServiceServer_HalfDuplexCall_Call struct {
	*mock.Call
}

// HalfDuplexCall is a helper method to define mock.On call
//   - bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]
func (_e *MockTestServiceServer_Expecter) HalfDuplexCall(bidiStreamingServer interface{}) *MockTestServiceServer_HalfDuplexCall_Call {
	return &MockTestServiceServer_HalfDuplexCall_Call{Call: _e.mock.On("HalfDuplexCall", bidiStreamingServer)}
}

func (_c *MockTestServiceServer_HalfDuplexCall_Call) Run(run func(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse])) *MockTestServiceServer_HalfDuplexCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]
		if args[0] != nil {
			arg0 = args[0].(grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_HalfDuplexCall_Call) Return(err error) *MockTestServiceServer_HalfDuplexCall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestServiceServer_HalfDuplexCall_Call) RunAndReturn(run func(bidiStreamingServer grpc.BidiStreamingServer[grpc_testing.StreamingOutputCallRequest, grpc_testing.StreamingOutputCallResponse]) error) *MockTestServiceServer_HalfDuplexCall_Call {
	_c.Call.Return(run)
	return _c
}

// StreamingInputCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) StreamingInputCall(clientStreamingServer grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse]) error {
	ret := _mock.Called(clientStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for StreamingInputCall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse]) error); ok {
		r0 = returnFunc(clientStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestServiceServer_StreamingInputCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamingInputCall'
type MockTestServiceServer_StreamingInputCall_Call struct {
	*mock.Call
}

// StreamingInputCall is a helper method to define mock.On call
//   - clientStreamingServer grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse]
func (_e *MockTestServiceServer_Expecter) StreamingInputCall(clientStreamingServer interface{}) *MockTestServiceServer_StreamingInputCall_Call {
	return &MockTestServiceServer_StreamingInputCall_Call{Call: _e.mock.On("StreamingInputCall", clientStreamingServer)}
}

func (_c *MockTestServiceServer_StreamingInputCall_Call) Run(run func(clientStreamingServer grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse])) *MockTestServiceServer_StreamingInputCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse]
		if args[0] != nil {
			arg0 = args[0].(grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_StreamingInputCall_Call) Return(err error) *MockTestServiceServer_StreamingInputCall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestServiceServer_StreamingInputCall_Call) RunAndReturn(run func(clientStreamingServer grpc.ClientStreamingServer[grpc_testing.StreamingInputCallRequest, grpc_testing.StreamingInputCallResponse]) error) *MockTestServiceServer_StreamingInputCall_Call {
	_c.Call.Return(run)
	return _c
}

// StreamingOutputCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) StreamingOutputCall(streamingOutputCallRequest *grpc_testing.StreamingOutputCallRequest, serverStreamingServer grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse]) error {
	ret := _mock.Called(streamingOutputCallRequest, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for StreamingOutputCall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*grpc_testing.StreamingOutputCallRequest, grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse]) error); ok {
		r0 = returnFunc(streamingOutputCallRequest, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTestServiceServer_StreamingOutputCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamingOutputCall'
type MockTestServiceServer_StreamingOutputCall_Call struct {
	*mock.Call
}

// StreamingOutputCall is a helper method to define mock.On call
//   - streamingOutputCallRequest *grpc_testing.StreamingOutputCallRequest
//   - serverStreamingServer grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse]
func (_e *MockTestServiceServer_Expecter) StreamingOutputCall(streamingOutputCallRequest interface{}, serverStreamingServer interface{}) *MockTestServiceServer_StreamingOutputCall_Call {
	return &MockTestServiceServer_StreamingOutputCall_Call{Call: _e.mock.On("StreamingOutputCall", streamingOutputCallRequest, serverStreamingServer)}
}

func (_c *MockTestServiceServer_StreamingOutputCall_Call) Run(run func(streamingOutputCallRequest *grpc_testing.StreamingOutputCallRequest, serverStreamingServer grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse])) *MockTestServiceServer_StreamingOutputCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *grpc_testing.StreamingOutputCallRequest
		if args[0] != nil {
			arg0 = args[0].(*grpc_testing.StreamingOutputCallRequest)
		}
		var arg1 grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_StreamingOutputCall_Call) Return(err error) *MockTestServiceServer_StreamingOutputCall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTestServiceServer_StreamingOutputCall_Call) RunAndReturn(run func(streamingOutputCallRequest *grpc_testing.StreamingOutputCallRequest, serverStreamingServer grpc.ServerStreamingServer[grpc_testing.StreamingOutputCallResponse]) error) *MockTestServiceServer_StreamingOutputCall_Call {
	_c.Call.Return(run)
	return _c
}

// UnaryCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) UnaryCall(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error) {
	ret := _mock.Called(context1, simpleRequest)

	if len(ret) == 0 {
		panic("no return value specified for UnaryCall")
	}

	var r0 *grpc_testing.SimpleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error)); ok {
		return returnFunc(context1, simpleRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.SimpleRequest) *grpc_testing.SimpleResponse); ok {
		r0 = returnFunc(context1, simpleRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc_testing.SimpleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc_testing.SimpleRequest) error); ok {
		r1 = returnFunc(context1, simpleRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestServiceServer_UnaryCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnaryCall'
type MockTestServiceServer_UnaryCall_Call struct {
	*mock.Call
}

// UnaryCall is a helper method to define mock.On call
//   - context1 context.Context
//   - simpleRequest *grpc_testing.SimpleRequest
func (_e *MockTestServiceServer_Expecter) UnaryCall(context1 interface{}, simpleRequest interface{}) *MockTestServiceServer_UnaryCall_Call {
	return &MockTestServiceServer_UnaryCall_Call{Call: _e.mock.On("UnaryCall", context1, simpleRequest)}
}

func (_c *MockTestServiceServer_UnaryCall_Call) Run(run func(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest)) *MockTestServiceServer_UnaryCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc_testing.SimpleRequest
		if args[1] != nil {
			arg1 = args[1].(*grpc_testing.SimpleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_UnaryCall_Call) Return(simpleResponse *grpc_testing.SimpleResponse, err error) *MockTestServiceServer_UnaryCall_Call {
	_c.Call.Return(simpleResponse, err)
	return _c
}

func (_c *MockTestServiceServer_UnaryCall_Call) RunAndReturn(run func(context1 context.Context, simpleRequest *grpc_testing.SimpleRequest) (*grpc_testing.SimpleResponse, error)) *MockTestServiceServer_UnaryCall_Call {
	_c.Call.Return(run)
	return _c
}

// UnimplementedCall provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) UnimplementedCall(context1 context.Context, empty *grpc_testing.Empty) (*grpc_testing.Empty, error) {
	ret := _mock.Called(context1, empty)

	if len(ret) == 0 {
		panic("no return value specified for UnimplementedCall")
	}

	var r0 *grpc_testing.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.Empty) (*grpc_testing.Empty, error)); ok {
		return returnFunc(context1, empty)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *grpc_testing.Empty) *grpc_testing.Empty); ok {
		r0 = returnFunc(context1, empty)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc_testing.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *grpc_testing.Empty) error); ok {
		r1 = returnFunc(context1, empty)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTestServiceServer_UnimplementedCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnimplementedCall'
type MockTestServiceServer_UnimplementedCall_Call struct {
	*mock.Call
}

// UnimplementedCall is a helper method to define mock.On call
//   - context1 context.Context
//   - empty *grpc_testing.Empty
func (_e *MockTestServiceServer_Expecter) UnimplementedCall(context1 interface{}, empty interface{}) *MockTestServiceServer_UnimplementedCall_Call {
	return &MockTestServiceServer_UnimplementedCall_Call{Call: _e.mock.On("UnimplementedCall", context1, empty)}
}

func (_c *MockTestServiceServer_UnimplementedCall_Call) Run(run func(context1 context.Context, empty *grpc_testing.Empty)) *MockTestServiceServer_UnimplementedCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *grpc_testing.Empty
		if args[1] != nil {
			arg1 = args[1].(*grpc_testing.Empty)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTestServiceServer_UnimplementedCall_Call) Return(empty1 *grpc_testing.Empty, err error) *MockTestServiceServer_UnimplementedCall_Call {
	_c.Call.Return(empty1, err)
	return _c
}

func (_c *MockTestServiceServer_UnimplementedCall_Call) RunAndReturn(run func(context1 context.Context, empty *grpc_testing.Empty) (*grpc_testing.Empty, error)) *MockTestServiceServer_UnimplementedCall_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedTestServiceServer provides a mock function for the type MockTestServiceServer
func (_mock *MockTestServiceServer) mustEmbedUnimplementedTestServiceServer() {
	_mock.Called()
	return
}

// MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedTestServiceServer'
type MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedTestServiceServer is a helper method to define mock.On call
func (_e *MockTestServiceServer_Expecter) mustEmbedUnimplementedTestServiceServer() *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	return &MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedTestServiceServer")}
}

func (_c *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Run(run func()) *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) Return() *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call) RunAndReturn(run func()) *MockTestServiceServer_mustEmbedUnimplementedTestServiceServer_Call {
	_c.Run(run)
	return _c
}
